### ISSUE TITLE
Make plugin check whether the ini key is valid. If not default to key "xyz"

### ISSUE THREAD

**Issue by Lenny-del** [Lenny-del/TrunkControl#18]

**Comment by Pjoottr** [comment]
What do you mean by "xyz"?

**Comment by Jeffduhdawg** [comment]
Whatever default key he's planning on putting.

**Comment by Pjoottr** [comment]
```cs
TrunkKey = ini.ReadEnum("Keys", "TrunkKey", Keys.T);
```

The last variable is a default key, if the read key is not in the enumeration it will return the default key. So in this case `Keys.T`

**Comment by Lenny-del** [comment]
https://github.com/Lenny-del/TrunkControl/issues/18#issuecomment-1006792309
